### 矩阵向量乘法

In [5]:
import numpy as np

A = np.array([[1,3], [4,0], [2,1]])
b = np.array([[1], [5]])

In [6]:
# dot 函数表示矩阵乘法(常用)
np.dot(A, b)

array([[16],
       [ 4],
       [ 7]])

In [7]:
# matmul 函数表示矩阵乘法
np.matmul(A, b)

array([[16],
       [ 4],
       [ 7]])

In [8]:
# python3 可以用 @ 符号直接对两个 ndarray 对象执行矩阵乘法
A @ b

array([[16],
       [ 4],
       [ 7]])

### numpy 矩阵乘法运算
- 元素乘法：np.multiply(a,b)
- 矩阵乘法：np.dot(a,b) 或 np.matmul(a,b) 或 a.dot(b) 或直接用 a @ b
- 唯独注意：*，在 np.array 中重载为元素乘法，在 np.matrix 中重载为矩阵乘法

### 矩阵乘法的特征

- 矩阵乘法不满足交换率 $A\times B \neq B\times A$
- 矩阵乘法满足结合律 $(A\times B)\times C = A\times (B\times C)$
- 单位矩阵运算 $A\times I = A , I \times A = A$

### 逆矩阵

$A$ 是方阵，如果存在 $A^{-1}$ 使得 $AA^{-1} = A^{-1}A = I$ 则称 $A^{-1}$ 为 $A$ 的逆矩阵

In [16]:
A = np.array([[3,4], [2,16]])
A

array([[ 3,  4],
       [ 2, 16]])

In [17]:
inv_A = np.linalg.inv(A)
inv_A

array([[ 0.4  , -0.1  ],
       [-0.05 ,  0.075]])

In [14]:
np.dot(A, inv_A)  # 矩阵乘以它的逆为单位阵

array([[1., 0.],
       [0., 1.]])

### 转置矩阵

In [15]:
# 方法1，调用transpose函数
np.transpose(A)

array([[ 3,  2],
       [ 4, 16]])

In [18]:
#方法2，使用T属性
A.T

array([[ 3,  2],
       [ 4, 16]])